-- Eurovision 2026 participating countries (code + name + flag).
-- Artist, song, running_order, semi_or_final, vibe_blurb, fun_fact are populated
-- per-show via /admin/setup JSON paste.
INSERT INTO countries (code, name, flag_emoji) VALUES
  ('AL', 'Albania',         '🇦🇱'),
  ('AM', 'Armenia',         '🇦🇲'),
  ('AU', 'Australia',       '🇦🇺'),
  ('AT', 'Austria',         '🇦🇹'),
  ('AZ', 'Azerbaijan',      '🇦🇿'),
  ('BE', 'Belgium',         '🇧🇪'),
  ('HR', 'Croatia',         '🇭🇷'),
  ('CY', 'Cyprus',          '🇨🇾'),
  ('CZ', 'Czechia',         '🇨🇿'),
  ('DK', 'Denmark',         '🇩🇰'),
  ('EE', 'Estonia',         '🇪🇪'),
  ('FI', 'Finland',         '🇫🇮'),
  ('FR', 'France',          '🇫🇷'),
  ('GE', 'Georgia',         '🇬🇪'),
  ('DE', 'Germany',         '🇩🇪'),
  ('GR', 'Greece',          '🇬🇷'),
  ('IS', 'Iceland',         '🇮🇸'),
  ('IE', 'Ireland',         '🇮🇪'),
  ('IL', 'Israel',          '🇮🇱'),
  ('IT', 'Italy',           '🇮🇹'),
  ('LV', 'Latvia',          '🇱🇻'),
  ('LT', 'Lithuania',       '🇱🇹'),
  ('LU', 'Luxembourg',      '🇱🇺'),
  ('MT', 'Malta',           '🇲🇹'),
  ('MD', 'Moldova',         '🇲🇩'),
  ('ME', 'Montenegro',      '🇲🇪'),
  ('NL', 'Netherlands',     '🇳🇱'),
  ('MK', 'North Macedonia', '🇲🇰'),
  ('NO', 'Norway',          '🇳🇴'),
  ('PL', 'Poland',          '🇵🇱'),
  ('PT', 'Portugal',        '🇵🇹'),
  ('SM', 'San Marino',      '🇸🇲'),
  ('RS', 'Serbia',          '🇷🇸'),
  ('SI', 'Slovenia',        '🇸🇮'),
  ('ES', 'Spain',           '🇪🇸'),
  ('SE', 'Sweden',          '🇸🇪'),
  ('CH', 'Switzerland',     '🇨🇭'),
  ('UA', 'Ukraine',         '🇺🇦'),
  ('GB', 'United Kingdom',  '🇬🇧'),
  ('BG', 'Bulgaria',        '🇧🇬');
